### ISSUE TITLE
Updates 

### ISSUE THREAD

**Issue by captainalvarez** [calvarium/homebridge-lifx-plugin#10]
The home app is showing that I have updates available for my light strips, but when I go to the LIFX app, everything is up to date. This is the case whether I have updates under advanced features checked or not.

**Comment by calvarium** [comment]
Hello @captainalvarez,

Can you give me some more information? What version of your strips is displayed in the HomeKit app, what version do your strips currently have?

I found out that in some cases it is necessary to add the corresponding bulbs again, because the HomeKit app caches the firmware versions and does not overwrite them when they are actually removed by my plugin. 
You can add your bulbs to the exclusion list, restart the homebridge and clear the list again. After a restart no firmware should be stored in the HomeKit app and is therefore no longer checked by the app.
